#!/bin/sh

DEFAULT_DIR="/home/lava/default-config"
CONFIG_DIR="/home/lava/printer_data/config"

start() {
    if [ -f /mnt/udisk/extended-recover.txt ]; then
        EXTENDED_DIR="$CONFIG_DIR/extended"

        # Move existing extended config to a backup location
        # find the next available backup number
        if [ -d "$EXTENDED_DIR" ]; then
            BACKUP_NUM=1
            while [ -d "$EXTENDED_DIR.backup.$BACKUP_NUM" ]; do
                BACKUP_NUM=$((BACKUP_NUM + 1))
            done
            mv "$EXTENDED_DIR" "$EXTENDED_DIR.backup.$BACKUP_NUM"
        fi
        rm -f /mnt/udisk/extended-recover.txt
    fi

    mkdir -p "$CONFIG_DIR"

    # Delete old files with matching checksums to force cleanup
    echo "Performing forced cleanup of old config files..."
    pushd "$CONFIG_DIR"
    sha256sum -c /usr/local/share/firmware-config/force-cleanup.sha256 | \
        awk -F':' '/: OK/{print $1}' |
        xargs -r rm -v --
    popd

    # Copy default config files without overwriting existing ones
    echo "Copying default config files..."
    cp -rn "$DEFAULT_DIR/." "$CONFIG_DIR/"

    # Remove old .default files and create new ones for files that differ
    echo "Updating .default files..."
    find "$CONFIG_DIR/extended" -name "*.default" -exec rm -v {} +
    pushd "$DEFAULT_DIR/extended" > /dev/null
    diff -rq . "$CONFIG_DIR/extended" \
        | sed -n 's/^Files \.\/\(.*\) and .* differ$/\1/p' \
        | xargs -I{} cp -v {} "$CONFIG_DIR/extended/{}.default"
    popd > /dev/null

    echo "Setting ownership to lava user..."
    chown -R lava:lava "$CONFIG_DIR"
}

case "$1" in
    start)
        start
        ;;
    stop)
        ;;
    restart|reload)
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
